# Generated by Django 3.0.1 on 2020-02-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prof_pic',
            new_name='image',
        ),
    ]
